# Generated by Django 3.2.8 on 2022-07-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='database',
            name='database_type_9a2b4d_idx',
        ),
    ]
