# Generated by Django 3.2.8 on 2022-07-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_database_database_type_9a2b4d_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='database',
            name='database_type_9a2b4d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together=set(),
        ),
    ]
