# Generated by Django 3.2.8 on 2022-07-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20220722_0955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('id', 'type', 'host', 'dbname')},
        ),
    ]
