# Generated by Django 3.2.8 on 2022-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_database_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='redis',
            name='db',
            field=models.CharField(default=1, max_length=64, verbose_name='数据库'),
        ),
    ]
