# Generated by Django 3.2.8 on 2022-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_redis_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redis',
            name='db',
            field=models.SmallIntegerField(default=1, max_length=64, verbose_name='数据库'),
        ),
    ]
