# Generated by Django 3.2.8 on 2022-07-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_redis_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='password',
            field=models.CharField(max_length=64, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='redis',
            name='db',
            field=models.SmallIntegerField(default=1, verbose_name='数据库'),
        ),
        migrations.AlterField(
            model_name='redis',
            name='password',
            field=models.CharField(max_length=64, null=True, verbose_name='密码'),
        ),
    ]
