# Generated by Django 3.2.8 on 2022-07-13 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='project',
            field=models.ManyToManyField(to='api.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.templates', verbose_name='模板'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='testsuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suit_case', to='api.testsuit', verbose_name='用例集合'),
        ),
        migrations.AddField(
            model_name='templates',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='sql',
            name='case',
            field=models.ManyToManyField(to='api.TestCase', verbose_name='所涉用例'),
        ),
        migrations.AddField(
            model_name='sql',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_scenario', to='api.testcase', verbose_name='测试函数（用例）'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddIndex(
            model_name='executionrequestbackup',
            index=models.Index(fields=['code'], name='api_executi_code_40bae5_idx'),
        ),
        migrations.AddIndex(
            model_name='executionrecord',
            index=models.Index(fields=['code'], name='api_executi_code_015b30_idx'),
        ),
        migrations.AddIndex(
            model_name='crontabexecid',
            index=models.Index(fields=['code'], name='api_crontab_code_6d438e_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['case'], name='api_testcas_case_97d46b_idx'),
        ),
        migrations.AddIndex(
            model_name='templates',
            index=models.Index(fields=['name'], name='api_templat_name_3c2472_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['scenario'], name='api_scenari_scenari_1e915d_idx'),
        ),
    ]
