# Generated by Django 3.2.8 on 2022-07-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='testsuit',
            name='project',
            field=models.ManyToManyField(to='api.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.templates', verbose_name='模板'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='testsuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suit_case', to='api.testsuit', verbose_name='用例集合'),
        ),
        migrations.AddField(
            model_name='templates',
            name='dbinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dbinfo_template', to='public.database', verbose_name='数据库信息配置'),
        ),
        migrations.AddField(
            model_name='templates',
            name='ftp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ftp_template', to='public.ftp', verbose_name='FTP配置'),
        ),
        migrations.AddField(
            model_name='templates',
            name='mq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mq_template', to='public.rabbitmq', verbose_name='RabbitMQ信息配置'),
        ),
        migrations.AddField(
            model_name='templates',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='templates',
            name='redis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redis_template', to='public.redis', verbose_name='REDIS配置'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_scenario', to='api.testcase', verbose_name='测试函数（用例）'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddIndex(
            model_name='executionrequestbackup',
            index=models.Index(fields=['code'], name='request_bac_code_85d3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='executionrecord',
            index=models.Index(fields=['code'], name='record_code_ea7cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='crontabexecid',
            index=models.Index(fields=['code'], name='crontab_exe_code_2cf70d_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['case'], name='case_case_1b6f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='templates',
            index=models.Index(fields=['name'], name='templates_name_061fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['scenario'], name='scenario_scenari_190d31_idx'),
        ),
    ]
