# Generated by Django 3.2.8 on 2022-06-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionrecord',
            options={'ordering': ('-update_time',), 'verbose_name_plural': '执行请求备份'},
        ),
    ]
