# Generated by Django 3.2.8 on 2022-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_executionrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRequestBackup',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='执行编码')),
                ('body', models.JSONField(verbose_name='请求体')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '执行请求备份',
                'ordering': ('-update_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='executionrecord',
            options={'ordering': ('-update_time',), 'verbose_name_plural': '执行记录'},
        ),
    ]
