# Generated by Django 3.2.8 on 2022-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220624_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrecord',
            name='loop_interval',
            field=models.SmallIntegerField(null=True, verbose_name='轮询任务时间间隔'),
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='stick_start_point',
            field=models.DateTimeField(null=True, verbose_name='定时任务时间点'),
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='task_type',
            field=models.SmallIntegerField(choices=[(0, '普通任务'), (1, '定时任务'), (2, '轮询任务')], default=0, verbose_name='任务类型'),
        ),
    ]
