# Generated by Django 3.2.8 on 2022-07-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_executionrecord_cron_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrecord',
            name='cron_task_status',
            field=models.SmallIntegerField(choices=[(1, '运行中'), (2, '已结束'), (3, '暂停'), (4, '已删除'), (5, '过期')], default=None, null=True, verbose_name='类型'),
        ),
    ]
