# Generated by Django 3.2.8 on 2022-07-23 16:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('_id', models.CharField(auto_created=True, default=user.models.UUIDTools.uuid4_hex, editable=False, max_length=64, unique=True, verbose_name='UID')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='菜单名称')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='菜单标题')),
                ('icon', models.CharField(default='SetUp', max_length=64, verbose_name='图标')),
                ('pid', models.SmallIntegerField(default=0, verbose_name='父级菜单')),
                ('path', models.CharField(max_length=128, verbose_name='菜单路径')),
                ('order', models.SmallIntegerField(default=0, verbose_name='菜单排序')),
            ],
            options={
                'verbose_name_plural': '菜单',
                'db_table': 'menu',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('_id', models.CharField(auto_created=True, default=user.models.UUIDTools.uuid4_hex, max_length=64, primary_key=True, serialize=False, verbose_name='UID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('describe', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述信息')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('menu', models.ManyToManyField(to='user.Menu', verbose_name='拥有菜单')),
            ],
            options={
                'verbose_name_plural': '角色表',
                'db_table': 'role',
                'ordering': ('-update_time',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', models.CharField(auto_created=True, default=user.models.UUIDTools.uuid4_hex, editable=False, max_length=64, unique=True, verbose_name='UID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('statue', models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='超级用户')),
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2, verbose_name='性别')),
                ('upload', models.ImageField(default='icon/avatar.jpg/', max_length=512, upload_to='icon', verbose_name='头像')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('role', models.ManyToManyField(to='user.Role', verbose_name='角色')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
                'db_table': 'user',
                'ordering': ('-create_time',),
            },
        ),
    ]
