# Generated by Django 3.2.8 on 2022-07-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220714_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='statue',
            field=models.SmallIntegerField(choices=[(0, '作废'), (1, '有效')], default=1, verbose_name='状态'),
        ),
    ]
