# Generated by Django 3.2.8 on 2022-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_role_statue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upload',
            field=models.ImageField(default='icon/default.png', max_length=512, upload_to='icon', verbose_name='头像'),
        ),
    ]
